### ISSUE TITLE
 kakao is not defined

### ISSUE THREAD

**Issue by dongguJeong** [layout-SY/DaeBang#60]
Uncaught ReferenceError: kakao is not defined
    at Map.tsx:48:10
    at Map.tsx:108:17

<img width="1409" alt="스크린샷 2024-11-28 오후 11 20 54" src="https://github.com/user-attachments/assets/d9c25b10-805b-46b1-90d9-b58fae06394b">

**Comment by dongguJeong** [comment]
vercel로 배포중인데 에러가 뜨네요
